package com.lxhf.frame.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lxhf.frame.bean.Baby;
import com.lxhf.frame.bean.User;

import com.lxhf.frame.db.greendao.BabyDao;
import com.lxhf.frame.db.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig babyDaoConfig;
    private final DaoConfig userDaoConfig;

    private final BabyDao babyDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        babyDaoConfig = daoConfigMap.get(BabyDao.class).clone();
        babyDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        babyDao = new BabyDao(babyDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Baby.class, babyDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        babyDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public BabyDao getBabyDao() {
        return babyDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
